"""할일, 메모 스키마 추가

Revision ID: 21b5c34cb1bb
Revises: b56ce40422f9
Create Date: 2026-03-05 16:03:09.072679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b5c34cb1bb'
down_revision: Union[str, Sequence[str], None] = 'b56ce40422f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.Text(), server_default=sa.text("'제목 없는 메모'"), nullable=False),
    sa.Column('content', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['embedding_id'], ['event_embeddings_base.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memos_owner_updated', 'memos', ['owner_user_id', 'updated_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_memos_owner_user_id'), 'memos', ['owner_user_id'], unique=False)
    op.create_table('todos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'TODO'"), nullable=False),
    sa.Column('priority', sa.String(length=16), server_default=sa.text("'normal'"), nullable=False),
    sa.Column('project', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("priority IN ('urgent', 'high', 'normal')", name='ck_todos_priority'),
    sa.CheckConstraint("status IN ('TODO', 'DONE')", name='ck_todos_status'),
    sa.ForeignKeyConstraint(['embedding_id'], ['event_embeddings_base.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_todos_owner_status', 'todos', ['owner_user_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_todos_owner_status_sort', 'todos', ['owner_user_id', 'status', 'sort_order'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_todos_owner_user_id'), 'todos', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###

    # -- 메모 GIN 전문 검색 인덱스 (title + content) --
    op.execute("""
      CREATE INDEX ix_memos_search ON public.memos
        USING GIN (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(content, '')))
        WHERE deleted_at IS NULL;
    """)

    # -- updated_at 자동 갱신 트리거 함수 (이미 존재할 수 있으므로 CREATE OR REPLACE) --
    op.execute("""
      CREATE OR REPLACE FUNCTION public.update_updated_at_column()
      RETURNS TRIGGER AS $$
      BEGIN
        NEW.updated_at = NOW();
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;
    """)

    # -- todos 트리거 --
    op.execute("""
      CREATE TRIGGER trigger_todos_updated_at
        BEFORE UPDATE ON public.todos
        FOR EACH ROW
        EXECUTE FUNCTION public.update_updated_at_column();
    """)

    # -- memos 트리거 --
    op.execute("""
      CREATE TRIGGER trigger_memos_updated_at
        BEFORE UPDATE ON public.memos
        FOR EACH ROW
        EXECUTE FUNCTION public.update_updated_at_column();
    """)

    # ===== todos 권한 및 RLS =====
    op.execute("REVOKE ALL ON TABLE public.todos FROM anon;")
    op.execute("REVOKE ALL ON SEQUENCE public.todos_id_seq FROM anon;")

    op.execute("REVOKE ALL ON TABLE public.todos FROM authenticated;")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.todos TO authenticated;")
    op.execute("REVOKE ALL ON SEQUENCE public.todos_id_seq FROM authenticated;")
    op.execute("GRANT USAGE, SELECT ON SEQUENCE public.todos_id_seq TO authenticated;")

    op.execute("REVOKE ALL ON TABLE public.todos FROM service_role;")
    op.execute("GRANT ALL ON TABLE public.todos TO service_role;")
    op.execute("REVOKE ALL ON SEQUENCE public.todos_id_seq FROM service_role;")
    op.execute("GRANT ALL ON SEQUENCE public.todos_id_seq TO service_role;")

    op.execute("ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;")

    op.execute("""
      CREATE POLICY todos_select_own ON public.todos
        FOR SELECT TO authenticated
        USING (owner_user_id = (select auth.uid()));
    """)
    op.execute("""
      CREATE POLICY todos_insert_own ON public.todos
        FOR INSERT TO authenticated
        WITH CHECK (owner_user_id = (select auth.uid()));
    """)
    op.execute("""
      CREATE POLICY todos_update_own ON public.todos
        FOR UPDATE TO authenticated
        USING (owner_user_id = (select auth.uid()))
        WITH CHECK (owner_user_id = (select auth.uid()));
    """)
    op.execute("""
      CREATE POLICY todos_delete_own ON public.todos
        FOR DELETE TO authenticated
        USING (owner_user_id = (select auth.uid()));
    """)

    # ===== memos 권한 및 RLS =====
    op.execute("REVOKE ALL ON TABLE public.memos FROM anon;")
    op.execute("REVOKE ALL ON SEQUENCE public.memos_id_seq FROM anon;")

    op.execute("REVOKE ALL ON TABLE public.memos FROM authenticated;")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.memos TO authenticated;")
    op.execute("REVOKE ALL ON SEQUENCE public.memos_id_seq FROM authenticated;")
    op.execute("GRANT USAGE, SELECT ON SEQUENCE public.memos_id_seq TO authenticated;")

    op.execute("REVOKE ALL ON TABLE public.memos FROM service_role;")
    op.execute("GRANT ALL ON TABLE public.memos TO service_role;")
    op.execute("REVOKE ALL ON SEQUENCE public.memos_id_seq FROM service_role;")
    op.execute("GRANT ALL ON SEQUENCE public.memos_id_seq TO service_role;")

    op.execute("ALTER TABLE public.memos ENABLE ROW LEVEL SECURITY;")

    op.execute("""
      CREATE POLICY memos_select_own ON public.memos
        FOR SELECT TO authenticated
        USING (owner_user_id = (select auth.uid()));
    """)
    op.execute("""
      CREATE POLICY memos_insert_own ON public.memos
        FOR INSERT TO authenticated
        WITH CHECK (owner_user_id = (select auth.uid()));
    """)
    op.execute("""
      CREATE POLICY memos_update_own ON public.memos
        FOR UPDATE TO authenticated
        USING (owner_user_id = (select auth.uid()))
        WITH CHECK (owner_user_id = (select auth.uid()));
    """)
    op.execute("""
      CREATE POLICY memos_delete_own ON public.memos
        FOR DELETE TO authenticated
        USING (owner_user_id = (select auth.uid()));
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # -- memos RLS 정책 제거 --
    op.execute("DROP POLICY IF EXISTS memos_delete_own ON public.memos;")
    op.execute("DROP POLICY IF EXISTS memos_update_own ON public.memos;")
    op.execute("DROP POLICY IF EXISTS memos_insert_own ON public.memos;")
    op.execute("DROP POLICY IF EXISTS memos_select_own ON public.memos;")
    op.execute("ALTER TABLE public.memos DISABLE ROW LEVEL SECURITY;")

    # -- memos 권한 복원 --
    op.execute("GRANT ALL ON TABLE public.memos TO anon;")
    op.execute("GRANT ALL ON TABLE public.memos TO authenticated;")
    op.execute("GRANT ALL ON TABLE public.memos TO service_role;")
    op.execute("GRANT ALL ON SEQUENCE public.memos_id_seq TO anon;")
    op.execute("GRANT ALL ON SEQUENCE public.memos_id_seq TO authenticated;")
    op.execute("GRANT ALL ON SEQUENCE public.memos_id_seq TO service_role;")

    # -- todos RLS 정책 제거 --
    op.execute("DROP POLICY IF EXISTS todos_delete_own ON public.todos;")
    op.execute("DROP POLICY IF EXISTS todos_update_own ON public.todos;")
    op.execute("DROP POLICY IF EXISTS todos_insert_own ON public.todos;")
    op.execute("DROP POLICY IF EXISTS todos_select_own ON public.todos;")
    op.execute("ALTER TABLE public.todos DISABLE ROW LEVEL SECURITY;")

    # -- todos 권한 복원 --
    op.execute("GRANT ALL ON TABLE public.todos TO anon;")
    op.execute("GRANT ALL ON TABLE public.todos TO authenticated;")
    op.execute("GRANT ALL ON TABLE public.todos TO service_role;")
    op.execute("GRANT ALL ON SEQUENCE public.todos_id_seq TO anon;")
    op.execute("GRANT ALL ON SEQUENCE public.todos_id_seq TO authenticated;")
    op.execute("GRANT ALL ON SEQUENCE public.todos_id_seq TO service_role;")

    # -- 트리거 제거 --
    op.execute("DROP TRIGGER IF EXISTS trigger_memos_updated_at ON public.memos;")
    op.execute("DROP TRIGGER IF EXISTS trigger_todos_updated_at ON public.todos;")

    # -- GIN 인덱스 제거 --
    op.execute("DROP INDEX IF EXISTS ix_memos_search;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_owner_user_id'), table_name='todos')
    op.drop_index('ix_todos_owner_status_sort', table_name='todos', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_todos_owner_status', table_name='todos', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('todos')
    op.drop_index(op.f('ix_memos_owner_user_id'), table_name='memos')
    op.drop_index('ix_memos_owner_updated', table_name='memos', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('memos')
    # ### end Alembic commands ###
