"""임베딩 벡터 외부 테이블 분리

Revision ID: b56ce40422f9
Revises: f2a4d3c1b8e9
Create Date: 2026-02-26 17:37:10.871543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b56ce40422f9'
down_revision: Union[str, Sequence[str], None] = 'f2a4d3c1b8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_embeddings_base',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_embeddings_base_model_name'), 'event_embeddings_base', ['model_name'], unique=False)
    op.create_table('event_embeddings_1024',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['event_embeddings_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_embeddings_1536',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['event_embeddings_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_embeddings_768',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['event_embeddings_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('google_calendar_events', sa.Column('embedding_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_google_calendar_events_description_trgm'), table_name='google_calendar_events', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin', postgresql_where='(description IS NOT NULL)')
    op.drop_index(op.f('ix_google_calendar_events_embedding_hnsw'), table_name='google_calendar_events', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw', postgresql_where='(embedding IS NOT NULL)')
    op.drop_index(op.f('ix_google_calendar_events_summary_trgm'), table_name='google_calendar_events', postgresql_ops={'summary': 'gin_trgm_ops'}, postgresql_using='gin', postgresql_where='(summary IS NOT NULL)')
    op.create_foreign_key('google_calendar_events_embedding_id_fkey', 'google_calendar_events', 'event_embeddings_base', ['embedding_id'], ['id'], ondelete='SET NULL')
    op.drop_column('google_calendar_events', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_calendar_events', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=True))
    op.drop_constraint('google_calendar_events_embedding_id_fkey', 'google_calendar_events', type_='foreignkey')
    op.create_index(op.f('ix_google_calendar_events_summary_trgm'), 'google_calendar_events', ['summary'], unique=False, postgresql_ops={'summary': 'gin_trgm_ops'}, postgresql_using='gin', postgresql_where='(summary IS NOT NULL)')
    op.create_index(op.f('ix_google_calendar_events_embedding_hnsw'), 'google_calendar_events', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw', postgresql_where='(embedding IS NOT NULL)')
    op.create_index(op.f('ix_google_calendar_events_description_trgm'), 'google_calendar_events', ['description'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin', postgresql_where='(description IS NOT NULL)')
    op.drop_column('google_calendar_events', 'embedding_id')
    op.drop_table('event_embeddings_768')
    op.drop_table('event_embeddings_1536')
    op.drop_table('event_embeddings_1024')
    op.drop_index(op.f('ix_event_embeddings_base_model_name'), table_name='event_embeddings_base')
    op.drop_table('event_embeddings_base')
    # ### end Alembic commands ###
