"""최초 스키마 생성

Revision ID: b8e6622c4a0c
Revises: 
Create Date: 2026-02-13 20:10:16.282220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e6622c4a0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('google_calendar_id', sa.String(length=320), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color_id', sa.String(length=32), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('start_payload', sa.JSON(), nullable=False),
    sa.Column('end_payload', sa.JSON(), nullable=False),
    sa.Column('reminders_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_calendar_id', 'google_event_id', name='uq_google_calendar_events_calendar_event')
    )
    op.create_index(op.f('ix_google_calendar_events_google_calendar_id'), 'google_calendar_events', ['google_calendar_id'], unique=False)
    op.create_index(op.f('ix_google_calendar_events_google_event_id'), 'google_calendar_events', ['google_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_calendar_events_google_event_id'), table_name='google_calendar_events')
    op.drop_index(op.f('ix_google_calendar_events_google_calendar_id'), table_name='google_calendar_events')
    op.drop_table('google_calendar_events')
    # ### end Alembic commands ###
