"""Add knowledge models

Revision ID: f6282e63e5db
Revises: a1b2c3d4e5f6
Create Date: 2026-03-25 15:44:42.655954

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "f6282e63e5db"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ==================================================================================================
# 지식 모델 스키마 추가
# --------------------------------------------------------------------------------------------------
# 지식 베이스 구축에 필요한 Knowledge 관련 테이블 생성
# ==================================================================================================
def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "knowledges",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
    sa.Column("title", sa.String(length=255), nullable=False),
    sa.Column("description", sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index("ix_knowledges_owner_deleted", "knowledges", ["user_id"], unique=False, postgresql_where=sa.text("deleted_at IS NULL"))
  op.create_index("ix_knowledges_title_desc_pgroonga", "knowledges", ["title", "description"], unique=False, postgresql_using="pgroonga")
  op.create_index(op.f("ix_knowledges_user_id"), "knowledges", ["user_id"], unique=False)
  op.create_table(
    "knowledge_sources",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("knowledge_id", sa.UUID(), nullable=False),
    sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
    sa.Column("source_type", sa.Enum("FILE", "WEB_URL", "TEXT_SNIPPET", name="sourcetype"), nullable=False),
    sa.Column("display_name", sa.String(length=255), nullable=False),
    sa.Column("storage_path", sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column("file_size", sa.Integer(), server_default=sa.text("0"), nullable=False),
    sa.Column("token_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
    sa.Column("mime_type", sa.String(length=255), server_default=sa.text("'application/octet-stream'"), nullable=False),
    sa.Column("status", sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", "DELETING", "DELETED", name="entitystatus"), nullable=False),
    sa.Column("error_message", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["knowledge_id"], ["knowledges.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index("ix_knowledge_sources_knowledge_id", "knowledge_sources", ["knowledge_id"], unique=False, postgresql_where=sa.text("deleted_at IS NULL"))
  op.create_index("ix_knowledge_sources_user_id", "knowledge_sources", ["user_id"], unique=False, postgresql_where=sa.text("deleted_at IS NULL"))
  op.create_table(
    "knowledge_chunks",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("source_id", sa.UUID(), nullable=False),
    sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
    sa.Column("chunk_index", sa.Integer(), nullable=False),
    sa.Column("chunk_content", sa.Text(), nullable=False),
    sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column("chunk_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(["source_id"], ["knowledge_sources.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index("ix_knowledge_chunks_content_pgroonga", "knowledge_chunks", ["chunk_content"], unique=False, postgresql_using="pgroonga")
  op.create_index(
    "ix_knowledge_chunks_embedding_hnsw",
    "knowledge_chunks",
    ["embedding"],
    unique=False,
    postgresql_using="hnsw",
    postgresql_with={"m": 16, "ef_construction": 64},
    postgresql_ops={"embedding": "vector_cosine_ops"},
  )
  op.create_index("ix_knowledge_chunks_source_id", "knowledge_chunks", ["source_id"], unique=False)
  # ### end Alembic commands ###


# ==================================================================================================
# 지식 모델 스키마 삭제
# --------------------------------------------------------------------------------------------------
# 지식 베이스용 Knowledge 관련 테이블 및 구조 제거
# ==================================================================================================
def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index("ix_knowledge_chunks_source_id", table_name="knowledge_chunks")
  op.drop_index(
    "ix_knowledge_chunks_embedding_hnsw",
    table_name="knowledge_chunks",
    postgresql_using="hnsw",
    postgresql_with={"m": 16, "ef_construction": 64},
    postgresql_ops={"embedding": "vector_cosine_ops"},
  )
  op.drop_index("ix_knowledge_chunks_content_pgroonga", table_name="knowledge_chunks", postgresql_using="pgroonga")
  op.drop_table("knowledge_chunks")
  op.drop_index("ix_knowledge_sources_user_id", table_name="knowledge_sources", postgresql_where=sa.text("deleted_at IS NULL"))
  op.drop_index("ix_knowledge_sources_knowledge_id", table_name="knowledge_sources", postgresql_where=sa.text("deleted_at IS NULL"))
  op.drop_table("knowledge_sources")
  op.drop_index(op.f("ix_knowledges_user_id"), table_name="knowledges")
  op.drop_index("ix_knowledges_title_desc_pgroonga", table_name="knowledges", postgresql_using="pgroonga")
  op.drop_index("ix_knowledges_owner_deleted", table_name="knowledges", postgresql_where=sa.text("deleted_at IS NULL"))
  op.drop_table("knowledges")
  # ### end Alembic commands ###
