from unittest.mock import AsyncMock
from unittest.mock import MagicMock
from unittest.mock import patch

import pytest
from httpx import AsyncClient


@pytest.mark.asyncio
async def test_embedding_success(client: AsyncClient, mock_supabase):
  """Embedding API returns embeddings generated by the EmbeddingService."""
  with patch("jwt.get_unverified_header") as mock_header, patch("jwt.decode") as mock_decode:
    mock_header.return_value = {"alg": "HS256"}
    mock_decode.return_value = {"sub": "user-123", "exp": 9999999999, "aud": "authenticated"}

    # 서버 사이드 검증 fallback을 위해 get_user 모킹
    mock_user = MagicMock()
    mock_user.id = "user-123"
    mock_supabase.auth.get_user.return_value.user = mock_user
    mock_table = MagicMock()
    mock_supabase.table.return_value = mock_table
    mock_table.select.return_value = mock_table
    mock_table.eq.return_value = mock_table
    mock_table.is_.return_value = mock_table
    mock_table.limit.return_value = mock_table
    mock_table.execute.return_value = MagicMock(data=[{"id": 1}])

    expected_embedding = [0.1, 0.2]
    with patch("app.api.v1.agent.embedding.EmbeddingService.embedding", new_callable=AsyncMock) as mock_embedding:
      mock_embedding.return_value = expected_embedding

      payload = {
        "entity": "GoogleCalendarEventModel",
        "summary": "hello",
        "description": "world",
        "start_at": "2026-03-05T00:00:00Z",
        "end_at": "2026-03-05T01:00:00Z",
      }
      headers = {"Authorization": "Bearer valid-token"}
      response = await client.post("/api/v1/agent/embedding", json=payload, headers=headers)

      assert response.status_code == 200
      body = response.json()
      assert body["result"] == expected_embedding
      assert body["error"] is False
      assert body["status"] == 200
      assert body["message"] == ""
      mock_embedding.assert_awaited_once()


@pytest.mark.asyncio
async def test_embedding_invalid_payload(client: AsyncClient, mock_supabase):
  """Embedding API rejects invalid payload missing entity."""
  with patch("jwt.get_unverified_header") as mock_header, patch("jwt.decode") as mock_decode:
    mock_header.return_value = {"alg": "HS256"}
    mock_decode.return_value = {"sub": "user-123", "exp": 9999999999, "aud": "authenticated"}

    # 서버 사이드 검증 fallback을 위해 get_user 모킹
    mock_user = MagicMock()
    mock_user.id = "user-123"
    mock_supabase.auth.get_user.return_value.user = mock_user

    payload = {
      "texts": ["hello"],
    }
    headers = {"Authorization": "Bearer valid-token"}
    response = await client.post("/api/v1/agent/embedding", json=payload, headers=headers)

    assert response.status_code == 422
